config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root 'home#index'

  resources :programs
  resources :requests

  devise_for :users, controllers: { registrations: "registrations"}



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
    
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:title, :owner, :date, :content, :decision)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def sign_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:owner, :date, :content, :decision)
    end
end

app/controllers/users_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<h1>Főoldal</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h4>Ez itt a kezdőlap. Az oldal folyamatos fejleszté alatt áll...</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hermannote</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">HermanNote</a>
        </div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li class=""><a href="/pages/info">Adatok</a></li>
            <li><a href="/requests">Kérvények</a></li>
            <li><a href="/programs">Programok</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

              <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                <%= current_user.name %></a></li>
              <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span></a></li> -->
              <li><%= link_to "Kilépés", destroy_user_session_path, :method => 'delete'%></li>

          </ul>
          <% else %>
            <!-- <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Regisztráció", new_registration_path(resource_name) %></li>
            </ul> -->

        <% end %>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <!-- <div>
      <% if user_signed_in? %>
        <p> Hello, <%= current_user.name%> <br><%= current_user.email %> - <%= link_to "Sign out", destroy_user_session_path, :method => 'delete'%> </p>
        <br>
      <% end %>
    </div> -->
  </body>
</html>

app/views/pages/info.html.erb
<h1>Adatok</h1>
<h3>Jegyzőkönyvet vezeti</h3>
<p><%= current_user.name %></p>

<h3>Jelenléti ív</h3>
<div>
  <p>Igazgató Úr: </br>
  <label class="checkbox-inline"><input type="checkbox" value="">Buzás Szilárd</label></p>
</div>
<div>
  <p>Kollégium Bizottság további tagjai:</br>

  <label class="checkbox-inline"><input type="checkbox" value="">Deáki Dominik</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Fürtön Petra</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Herczeg Rita</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Lipka Barbara</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Szalai Balázs</label></p>
</div>
<div>
  <p>Seniorok:</br>

  <label class="checkbox-inline"><input type="checkbox" value="">Fodor József</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Horváth András</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Ladányi Lálszló</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Ördög Katalin</label>
  <label class="checkbox-inline"><input type="checkbox" value="">Szilágyi Rómeó</label></p>
</div>

<h3>Következő ülés</h3>

  <!-- <input type="text" data-provide='datepicker' > -->
  <input type="text" >

app/views/programs/_form.html.erb
<%= form_for(program) do |f| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Név" %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :owner, "Szervező" %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <!-- <%= link_to "Refresh", "" %> -->
    <%= f.label :date, "Dátum" %>
    <%= f.text_field :date%>
  </div>

  <div class="field">
    <%= f.label :content, "Tartalom"%>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :decision, "Döntés" %>
    <%= f.text_area :decision %>
  </div>

  <div class="actions">
    <%= f.submit  'Mentés', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Program átírása</h1>

<%= render 'form', program: @program %>

<%= link_to 'Olvas', @program %> |
<%= link_to 'Vissza', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programok</h1>

<table>
  <thead>
    <tr>
      <th>Név</th>
      <th>Szervező</th>
      <th>Dátum</th>
      <th>Tartalom</th>
      <th>Döntés</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.title %></td>
        <td><%= program.owner %></td>
        <td><%= program.date %></td>
        <td><%= program.content %></td>
        <td><%= program.decision %></td>
        <td class="no-print"><%= link_to 'Olvas', program %></td>
        <td class="no-print"><%= link_to 'Átír', edit_program_path(program) %></td>
        <td class="no-print"><%= link_to 'Töröl', program, method: :delete, data: { confirm: 'Biztos törlöd?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Új Program', new_program_path,  class: 'btn btn-default btn-info no-print' %>

app/views/programs/new.html.erb
<h1>Új program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Vissza', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Név:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>Szervező:</strong>
  <%= @program.owner %>
</p>

<p>
  <strong>Dátum:</strong>
  <%= @program.date %>
</p>

<p>
  <strong>Tartalom:</strong>
  <%= @program.content %>
</p>

<p>
  <strong>Döntés:</strong>
  <%= @program.decision %>
</p>

<%= link_to 'Átír', edit_program_path(@program) %> |
<%= link_to 'Vissza', programs_path %>

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner, "Kérvényező" %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <%= f.label :date, "Dátum" %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :content, "Tartalom" %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :decision, "Döntés" %>
    <%= f.text_area :decision %>
  </div>

  <div class="actions">
      <%= f.submit  'Mentés', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Kérvények átírása</h1>

<%= render 'form', request: @request %>

<%= link_to 'Olvas', @request %> |
<%= link_to 'Vissza', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kérvények</h1>

<table>
  <thead>
    <tr>
      <th>Kérvényező</th>
      <th>Dátum</th>
      <th>Tartalom</th>
      <th>Döntés</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.owner %></td>
        <td><%= request.date %></td>
        <td><%= request.content %></td>
        <td><%= request.decision %></td>
        <td class="no-print"><%= link_to 'Olvas', request %></td>
        <td class="no-print"><%= link_to 'Átír', edit_request_path(request) %></td>
        <td class="no-print"><%= link_to 'Töröl', request, method: :delete, data: { confirm: 'Biztos törlöd?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Új Kérvény', new_request_path,  class: 'btn btn-default btn-info no-print' %>

app/views/requests/new.html.erb
<h1>Új kérvény</h1>

<%= render 'form', request: @request %>

<%= link_to 'Vissza', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kérvényező:</strong>
  <%= @request.owner %>
</p>

<p>
  <strong>Dátum:</strong>
  <%= @request.date %>
</p>

<p>
  <strong>Tartalom:</strong>
  <%= @request.content %>
</p>

<p>
  <strong>Döntés:</strong>
  <%= @request.decision %>
</p>

<%= link_to 'Átír', edit_request_path(@request) %> |
<%= link_to 'Vissza', requests_path %>